# Generated by Django 5.1.2 on 2024-10-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('voltaje', models.FloatField()),
                ('voltaje_corregido', models.FloatField()),
            ],
        ),
    ]
